### ISSUE TITLE
Weird error

### ISSUE THREAD

**Issue by justinhj** [hootsuite/akka-persistence-redis#8]
I have a project that runs fine from the command line using sbt run, but in IntelliJ IDE I get this error.

Any idea what could be going on?

[ERROR] [11/07/2015 18:43:05.379] [default-akka.persistence.dispatchers.default-plugin-dispatcher-7] [akka.actor.ActorSystemImpl(default)] Uncaught error from thread [default-akka.persistence.dispatchers.default-plugin-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled
Uncaught error from thread [default-akka.persistence.dispatchers.default-plugin-dispatcher-7] shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[default]
java.lang.AbstractMethodError: com.hootsuite.akka.persistence.redis.journal.RedisJournal.akka$persistence$journal$WriteJournalBase$_setter_$persistence_$eq(Lakka/persistence/Persistence;)V
java.lang.AbstractMethodError: com.hootsuite.akka.persistence.redis.journal.RedisJournal.akka$persistence$journal$WriteJournalBase$_setter_$persistence_$eq(Lakka/persistence/Persistence;)V
	at akka.persistence.journal.WriteJournalBase$class.$init$(WriteJournalBase.scala:15)
	at akka.persistence.journal.WriteJournalBase$class.$init$(WriteJournalBase.scala:15)
	at com.hootsuite.akka.persistence.redis.journal.RedisJournal.<init>(RedisJournal.scala:18)
	at com.hootsuite.akka.persistence.redis.journal.RedisJournal.<init>(RedisJournal.scala:18)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)

**Comment by hootsuitemike** [comment]
`java.lang.AbstractMethodError` usually appears when there is a runtime conflict with a library. I would make sure that the IntelliJ classpath is identical to the sbt one.

**Comment by justinhj** [comment]
Hi thanks for looking into it 

I found that cleaning up the target and rebuilding fixed the problem
